version: '3.7'

networks:
    default:
        driver: bridge

services:
#  test:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#      api:
#        condition: service_started
#    links:
#      - rabbitmq
  jupyter:
    image: quay.io/jupyter/datascience-notebook:2024-03-14
    container_name: troi-dev
    volumes:
      - ./:/home/jovyan/work
